[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.log

[program:scanner]
command=/app/scan_loop.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/scanner.log
stderr_logfile=/var/log/supervisor/scanner.log