[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startsecs=5                  ; give more time before considering started
stopsignal=QUIT
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:scanner]
command=/app/scan_loop.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/scanner.log
stderr_logfile=/var/log/supervisor/scanner.log